name: Capsule Validator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: actions/setup-powershell@v1

      - name: Run validator script
        shell: pwsh
        run: ./validate.ps1
